sudo: false
language: php

php:
 - 7.0
 - 7.1
 - 7.2
 - 7.3
 

matrix:
  fast_finish: true

before_script:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install

script:
 - php vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
