sudo: false
language: php

php:
 - 7.0
 - 7.1
 - 7.2
 - 7.3

matrix:
  fast_finish: true

before_script:
 - mkdir -p build/logs
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install

script:
 - php vendor/bin/phpunit -c . --coverage-clover build/logs/clover.xml
